defmodule Aoc.Day7Test do
  use ExUnit.Case

  import Aoc.Day7

  @input Inputs.read("day_7_input.txt")

  @example """
  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  """

  test "part 1 example", do: assert(part_1(@example) == 21)

  @tag :answer
  test "part 1 answer", do: assert(part_1(@input) == 1658)

  test "part 2 example", do: assert(part_2(@example) == 40)

  @tag :answer
  test "part 2 answer", do: assert(part_2(@input) == 53_916_299_384_254)
end
